In [1]:
# ============================================
# California Coastal Conditions Pipeline
# Stage 1 of 4: Clean the CalCOFI flat files
# Author: Brittany Blessie
# Description: Loads the CalCOFI Bottle and Cast CSVs, joins them on Cst_Cnt, and
#              applies labeled transformation steps to produce a clean coastal dataset.
# ============================================

In [2]:
import pandas as pd

In [3]:
cast = pd.read_csv("194903-202105_Cast.csv", low_memory=False)

In [4]:
cast.shape
cast.head()

,Cst_Cnt,Cruise_ID,Cruise,Cruz_Sta,DbSta_ID,Cast_ID,Sta_ID,Quarter,Sta_Code,Distance,...,Wave_Prd,Wind_Dir,Wind_Spd,Barometer,Dry_T,Wet_T,Wea,Cloud_Typ,Cloud_Amt,Visibility
0,1,1949-03-01-C-31CR,194903,19490305400560,5400560,19-4903CR-HY-060-0930-05400560,054.0 056.0,1,NST,NaN,...,NaN,23.0,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
1,2,1949-03-01-C-31CR,194903,19490305200750,5200750,19-4903CR-HY-060-2112-05200750,052.0 075.0,1,NST,NaN,...,NaN,16.0,5.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,3,1949-03-01-C-31CR,194903,19490305100850,5100850,19-4903CR-HY-061-0354-05100850,051.0 085.0,1,NST,NaN,...,NaN,23.0,5.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN
3,4,1949-03-01-C-31CR,194903,19490305000950,5000950,19-4903CR-HY-061-1042-05000950,050.0 095.0,1,NST,NaN,...,NaN,18.0,8.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
4,5,1949-03-01-C-31CR,194903,19490305001040,5001040,19-4903CR-HY-061-1706-05001040,050.0 104.0,1,NST,NaN,...,NaN,27.0,13.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN

In [5]:
cast.columns.tolist()

['Cst_Cnt',
 'Cruise_ID',
 'Cruise',
 'Cruz_Sta',
 'DbSta_ID',
 'Cast_ID',
 'Sta_ID',
 'Quarter',
 'Sta_Code',
 'Distance',
 'Date',
 'Year',
 'Month',
 'Julian_Date',
 'Julian_Day',
 'Time',
 'Lat_Dec',
 'Lat_Deg',
 'Lat_Min',
 'Lat_Hem',
 'Lon_Dec',
 'Lon_Deg',
 'Lon_Min',
 'Lon_Hem',
 'Rpt_Line',
 'St_Line',
 'Ac_Line',
 'Rpt_Sta',
 'St_Station',
 'Ac_Sta',
 'Bottom_D',
 'Secchi',
 'ForelU',
 'Ship_Name',
 'Ship_Code',
 'Data_Type',
 'Order_Occ',
 'Event_Num',
 'Cruz_Leg',
 'Orig_Sta_ID',
 'Data_Or',
 'Cruz_Num',
 'IntChl',
 'IntC14',
 'Inc_Str',
 'Inc_End',
 'PST_LAN',
 'Civil_T',
 'TimeZone',
 'Wave_Dir',
 'Wave_Ht',
 'Wave_Prd',
 'Wind_Dir',
 'Wind_Spd',
 'Barometer',
 'Dry_T',
 'Wet_T',
 'Wea',
 'Cloud_Typ',
 'Cloud_Amt',
 'Visibility']

## Step 1: Select Cast Columns
Keep only the join key, decimal coordinates, date, time, and station ID from the Cast file. Drops the other 55 columns that the project does not use.

In [6]:
# Step #1: Select only the columns needed from the Cast file.
# Keeps the join key, decimal coordinates, date/time, and station ID; drops the other 55 columns.
cast_clean = cast[["Cst_Cnt", "Lat_Dec", "Lon_Dec", "Date", "Time", "Sta_ID"]]
cast_clean.shape

(35644, 6)

In [7]:
bottle = pd.read_csv("194903-202105_Bottle.csv", encoding="latin1", low_memory=False)

In [8]:
bottle.shape
bottle.columns.tolist()

['Cst_Cnt',
 'Btl_Cnt',
 'Sta_ID',
 'Depth_ID',
 'Depthm',
 'T_degC',
 'Salnty',
 'O2ml_L',
 'STheta',
 'O2Sat',
 'Oxy_µmol/Kg',
 'BtlNum',
 'RecInd',
 'T_prec',
 'T_qual',
 'S_prec',
 'S_qual',
 'P_qual',
 'O_qual',
 'SThtaq',
 'O2Satq',
 'ChlorA',
 'Chlqua',
 'Phaeop',
 'Phaqua',
 'PO4uM',
 'PO4q',
 'SiO3uM',
 'SiO3qu',
 'NO2uM',
 'NO2q',
 'NO3uM',
 'NO3q',
 'NH3uM',
 'NH3q',
 'C14As1',
 'C14A1p',
 'C14A1q',
 'C14As2',
 'C14A2p',
 'C14A2q',
 'DarkAs',
 'DarkAp',
 'DarkAq',
 'MeanAs',
 'MeanAp',
 'MeanAq',
 'IncTim',
 'LightP',
 'R_Depth',
 'R_TEMP',
 'R_Sal',
 'R_DYNHT',
 'R_Nuts',
 'R_Oxy_µmol/Kg',
 'DIC1',
 'DIC2',
 'TA1',
 'TA2',
 'pH1',
 'pH2',
 'DIC Quality Comment']

## Step 2: Select Bottle Columns
Keep only the six needed columns from the Bottle file: the join key, the bottle ID, and the four ocean measurements (depth, temperature, salinity, oxygen). Drops the other 56 columns.

In [9]:
# Step #2: Keep only the six needed columns from the Bottle file and drop the other 56.
# These are the join key, the bottle ID, and the four ocean measurements (depth, temperature, salinity, oxygen).
bottle_clean = bottle[["Cst_Cnt", "Btl_Cnt", "Depthm", "T_degC", "Salnty", "O2ml_L"]]
bottle_clean.shape

(895371, 6)

## Step 3: Join Bottle and Cast on Cst_Cnt
Merge the Bottle and Cast tables on Cst_Cnt so every measurement carries the coordinates from its cast. This is a many-to-one join, since each cast has many bottle samples.

In [10]:
# Step #3: Join the Bottle and Cast tables on Cst_Cnt so every measurement carries its cast's coordinates.
# This is a many-to-one merge: many bottle rows attach to one cast row that shares the same Cst_Cnt.
merged = bottle_clean.merge(cast_clean, on="Cst_Cnt", how="left")
merged.shape

(895371, 11)

In [11]:
merged.isnull().sum()

Cst_Cnt         0
Btl_Cnt         0
Depthm          0
T_degC      10969
Salnty      47356
O2ml_L     169741
Lat_Dec         0
Lon_Dec         0
Date            0
Time         9929
Sta_ID          0
dtype: int64

## Step 4: Drop Rows Missing Measurements
Remove any row missing depth, temperature, salinity, or oxygen, since the analysis needs all four together. This drops about 204,000 incomplete rows and leaves complete records.

In [12]:
# Step #4: Drop rows missing any of the four ocean measurements.
# The analysis needs temperature, salinity, oxygen, and depth together, so only complete rows are kept.
merged_clean = merged.dropna(subset=["Depthm", "T_degC", "Salnty", "O2ml_L"])
merged_clean.shape

(690914, 11)

In [13]:
merged_clean.describe()

,Cst_Cnt,Btl_Cnt,Depthm,T_degC,Salnty,O2ml_L,Lat_Dec,Lon_Dec
count,690914.000000,690914.000000,690914.000000,690914.000000,690914.000000,690914.000000,690914.000000,690914.000000
mean,19089.233298,480581.914797,217.111334,10.931262,33.819091,3.423529,31.872818,-120.330169
std,10843.687987,265217.024806,306.323186,4.205196,0.537729,2.080619,3.522655,3.945389
min,71.000000,2161.000000,0.000000,1.440000,24.189670,-200.222000,18.416666,-157.983333
25%,10002.000000,259934.250000,49.000000,7.830000,33.478000,1.420000,30.283333,-122.533333
50%,21155.000000,521779.500000,125.000000,10.165000,33.844300,3.480000,32.417920,-120.375000
75%,28980.000000,717985.750000,298.000000,14.020000,34.180000,5.520000,33.724570,-118.113333
max,35644.000000,895398.000000,5351.000000,31.140000,37.034000,11.130000,47.916666,-105.966666

## Step 5: Remove Impossible Oxygen Values
Drop rows where oxygen is below zero. Negative oxygen is physically impossible, so these are placeholder or bad values that the missing-value step did not catch.

In [14]:
# Step #5: Remove physically impossible oxygen values.
# Oxygen cannot be negative, so rows with O2ml_L below 0 are placeholder/bad data and are dropped.
merged_clean = merged_clean[merged_clean["O2ml_L"] >= 0]
merged_clean.shape

(690909, 11)

## Step 6: Reset the Index
Renumber the rows from zero after the drops so the final dataset has a clean, continuous index.

In [15]:
# Step #6: Reset the row index after dropping rows so the final dataset is numbered cleanly from 0.
merged_clean = merged_clean.reset_index(drop=True)
merged_clean.shape

(690909, 11)

In [16]:
# Final cleaned and merged dataset (first 20 rows)
merged_clean.head(20)

,Cst_Cnt,Btl_Cnt,Depthm,T_degC,Salnty,O2ml_L,Lat_Dec,Lon_Dec,Date,Time,Sta_ID
0,71,2161,0,10.30,33.030,5.90,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
1,71,2162,6,18.46,32.920,6.02,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
2,71,2163,10,10.29,32.951,6.04,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
3,71,2164,15,10.29,32.990,6.06,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
4,71,2165,20,10.33,33.005,6.04,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
5,71,2166,30,10.39,33.054,6.01,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
6,71,2167,31,10.40,33.060,6.01,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
7,71,2168,47,10.36,33.150,5.78,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
8,71,2169,50,10.35,33.167,5.76,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
9,71,2170,64,10.25,33.260,5.60,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
10,71,2171,75,10.05,33.381,5.07,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
11,71,2172,98,9.54,33.640,3.82,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
12,71,2173,100,9.50,33.656,3.76,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
13,71,2174,125,9.05,33.810,3.20,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
14,71,2175,132,8.93,33.840,3.10,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
15,71,2176,150,8.66,33.891,2.71,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
16,71,2177,197,8.04,33.960,1.78,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
17,71,2178,200,8.01,33.966,1.74,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
18,71,2179,250,7.53,34.058,1.19,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
19,71,2180,300,7.11,34.136,0.81,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5

## Step 7: Rename Columns to Readable Names
Rename the abbreviated CalCOFI field names to clear labels with units, so the final dataset is understandable without a codebook. Columns like T_degC become Temperature_C and O2ml_L becomes Oxygen_mL_L.

In [17]:
# Step #7: Rename columns to clear, human-readable names.
# CalCOFI uses abbreviated field names, so this makes the final dataset understandable without a codebook.
merged_clean = merged_clean.rename(columns={
    "Cst_Cnt": "Cast_ID",
    "Btl_Cnt": "Bottle_ID",
    "Depthm": "Depth_m",
    "T_degC": "Temperature_C",
    "Salnty": "Salinity_PSU",
    "O2ml_L": "Oxygen_mL_L",
    "Lat_Dec": "Latitude",
    "Lon_Dec": "Longitude",
    "Sta_ID": "Station_ID"
})
merged_clean.head(20)

,Cast_ID,Bottle_ID,Depth_m,Temperature_C,Salinity_PSU,Oxygen_mL_L,Latitude,Longitude,Date,Time,Station_ID
0,71,2161,0,10.30,33.030,5.90,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
1,71,2162,6,18.46,32.920,6.02,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
2,71,2163,10,10.29,32.951,6.04,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
3,71,2164,15,10.29,32.990,6.06,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
4,71,2165,20,10.33,33.005,6.04,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
5,71,2166,30,10.39,33.054,6.01,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
6,71,2167,31,10.40,33.060,6.01,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
7,71,2168,47,10.36,33.150,5.78,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
8,71,2169,50,10.35,33.167,5.76,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
9,71,2170,64,10.25,33.260,5.60,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
10,71,2171,75,10.05,33.381,5.07,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
11,71,2172,98,9.54,33.640,3.82,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
12,71,2173,100,9.50,33.656,3.76,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
13,71,2174,125,9.05,33.810,3.20,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
14,71,2175,132,8.93,33.840,3.10,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
15,71,2176,150,8.66,33.891,2.71,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
16,71,2177,197,8.04,33.960,1.78,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
17,71,2178,200,8.01,33.966,1.74,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
18,71,2179,250,7.53,34.058,1.19,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5
19,71,2180,300,7.11,34.136,0.81,40.833333,-124.833333,03/28/1949,06:06:00,044.0 048.5

## Data Notes and Limitations

The transformations I made to the CalCOFI flat file were as follows: I selected a small set of columns from the Bottle and Cast files, joined the two on Cst_Cnt so every measurement carried its cast coordinates, dropped rows missing any of the four measurements, removed five rows with negative oxygen values that are physically impossible, and reset the index. On legal and regulatory guidelines, CalCOFI data is public research data collected by Scripps, NOAA, and California Fish and Wildlife, published for open scientific use, so there are no licensing restrictions and no personal information is involved. The main risk created by these transformations is that the cleaned file is now a subset of the full record, since dropping about 204,000 incomplete rows means anyone who treated this version as the complete CalCOFI archive could misjudge how much data exists or how the coast was sampled. As for assumptions, the biggest is that a row needed all four measurements to be useful, since the analysis compares them together. I also treated the negative oxygen readings as bad data rather than real values, because oxygen cannot be negative, and I assumed the coordinates recorded for each cast apply to all the bottles collected during that cast, which is how CalCOFI structures its sampling. On sourcing and credibility, I downloaded the data directly from the official CalCOFI website and checked each column meaning against their published field descriptions. The data was acquired ethically, since it is public data intended for research and I obtained it from the original source. To mitigate the risks I identified, I documented every transformation and the number of rows it affected inside the notebook, kept the original raw files so the complete data can always be recovered, and will describe the cleaned dataset as a subset rather than the full archive whenever I present it.

In [18]:
# Save the cleaned CalCOFI data for the merge stage
merged_clean.to_csv("calcofi_clean.csv", index=False)